appenders:
  my_file_logger:
    kind: rolling_file
    path: "log/byte_bite.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500kb
      roller:
        kind: delete
root:
  level: trace
  appenders:
    - my_file_logger